version: "3.9"

services:
  jupyterlab:
    image: jupyter/glances:test
    build:
      context: "."
      dockerfile: setup/Dockerfile
    container_name: jupyterlab
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "${PWD}:/home/jovyan/jupyter-glances-proxy"
